platform :ios, '6.0'
pod 'Evernote-SDK-iOS', '~> 1.3.1'
pod 'Mapbox-iOS-SDK', '~> 1.4.1'
pod 'Reachability', '~> 3.1.1'
pod 'MWPhotoBrowser', '~> 1.4.1'
pod 'ViewDeck', :git => 'https://github.com/drmarkpowell/ViewDeck'
pod 'PSMenuItem', '~> 0.0.1'
pod 'AFNetworking', '~> 2.0'
pod 'CHCSVParser', '~> 2.0'