platform :ios, '6.0'
pod 'Evernote-SDK-iOS', '~> 1.3'
pod 'UIImage-Categories', '~> 0.0.1'
pod 'Reachability', '~> 3.1.1'
pod 'MWPhotoBrowser', '~> 0.0.1' 
pod 'JASidePanels', '~> 1.3.2'
pod 'PSMenuItem', '~> 0.0.1'