# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :tests do
    run_tests(workspace: "MarsImagesIOS.xcworkspace", scheme: "MarsImagesIOS")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates
    get_provisioning_profile
    build_app(workspace: "MarsImagesIOS.xcworkspace", scheme: "MarsImagesIOS")
    upload_to_testflight
  end
end
